name: Make Release Artifacts

on:
   workflow_call:
    inputs:
        branch:
            type: string
            description: "The branch to create the release from"
            required: true
        node-version:
            type: string
            description: "The node version to use"
            required: true
        artifact-paths:
            type: string
            description: "The glob patters to find the release artifacts"
            required: true
        workflows-ref:
            type: string
            description: "The ref to run the workflow"
            required: false
            default: "master"

jobs:
  make-release-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GH context to log
        run: |
          echo "===== GITHUB CONTEXT ====="
          echo "${{ toJson(github) }}"
          echo "====

      - name: Checkout caller repo
        uses: actions/checkout@master
        with:
          ref: ${{ inputs.branch }}

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ inputs.node-version }}

      - name: run npm ci
        run: npm ci

      - name: Run package
        run: npm run package

      - name: Checkout the rokucommunity/workflows repo
        uses: actions/checkout@master
        with:
          repository: rokucommunity/workflows
          path: nested-ci
          ref: ${{ inputs.workflows-ref }}

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '18.18.2'

      - name: CD into nested-ci, run npm ci
        run: |
          cd nested-ci
          npm ci

      - name: Set RUNNER_DEBUG env variable
        run: |
          if [[ "$RUNNER_DEBUG" == "1" ]]; then
            echo "RUNNER_DEBUG=true" >> $GITHUB_ENV
          else
            echo "RUNNER_DEBUG=false" >> $GITHUB_ENV
          fi

      - name: Run make artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          npx ts-node nested-ci/src/cli.ts \
            make-release-artifacts \
            --branch "${{ inputs.branch }}" \
            --projectName "${{ github.repository }}" \
            --artifactPaths ${{ inputs.artifact-paths }}
