name: Publish Release

on:
   workflow_call:
    inputs:
        ref:
            type: string
            description: "The merge commit created when the pull request is merged"
            required: true
        release-type:
            type: string
            description: "The type of release. Can be 'npm` or 'vsce'"
            required: true
        workflows-ref:
            type: string
            description: "The ref to run the workflow"
            required: false
            default: "master"


jobs:
  publish-release:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the rokucommunity/workflows repo
        uses: actions/checkout@master
        with:
          repository: rokucommunity/workflows
          path: nested-ci
          ref: ${{ inputs.workflows-ref }}

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '18.18.2'

      - name: CD into nested-ci, run npm ci
        run: |
          cd nested-ci
          npm ci

      - name: Set RUNNER_DEBUG env variable
        run: |
          if [[ "$RUNNER_DEBUG" == "1" ]]; then
            echo "RUNNER_DEBUG=true" >> $GITHUB_ENV
          else
            echo "RUNNER_DEBUG=false" >> $GITHUB_ENV
          fi

      - name: Run publish
        env:
          GH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: |
          npx ts-node nested-ci/src/cli.ts \
            publish-release \
            --projectName "${{ github.repository }}" \
            --ref ${{ inputs.ref }} \
            --releaseType ${{ inputs.release-type }}
