name: Publish Release

on:
   workflow_call:
    inputs:
        branch:
            type: string
            description: "The branch to create the release from"
            required: true
        ref:
            type: string
            description: "The merge commit created when the pull request is merged"
            required: true
        release-type:
            type: string
            description: "The type of release. Can be 'npm` or 'vsce'"
            required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .github repo
        uses: actions/checkout@master
        with:
          repository: rokucommunity/workflows

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: "16.20.2"

      - name: Run npm ci
        run: npm ci

      - name: Set RUNNER_DEBUG env variable
        run: |
          if [[ "$RUNNER_DEBUG" == "1" ]]; then
            echo "RUNNER_DEBUG=true" >> $GITHUB_ENV
          else
            echo "RUNNER_DEBUG=false" >> $GITHUB_ENV
          fi
    
      - name: Run publish
        env:
          GH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: |
          npx ts-node src/cli.ts \
            publish-release \
            --branch "${{ inputs.branch }}" \
            --projectName "${{ github.repository }}" \
            --ref ${{ inputs.ref }} \
            --releaseType ${{ inputs.release-type }}