name: Publish Release

on:
   workflow_call:
    inputs:
        ref:
            type: string
            description: "The merge commit created when the pull request is merged"
            required: true
        release-type:
            type: string
            description: "The type of release. Can be 'npm` or 'vsce'"
            required: true
        workflows-ref:
            type: string
            description: "The ref to run the workflow"
            required: false
            default: "master"

jobs:
  publish-release:
    if: ${{ (github.event.pull_request.merged == true && github.event.pull_request.head.repo.full_name == github.event.repository.full_name) || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the rokucommunity/workflows repo
        uses: actions/checkout@master
        with:
          repository: rokucommunity/workflows
          path: nested-ci
          ref: ${{ inputs.workflows-ref }}

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '20.19.4'

      - name: Update npm to support trusted publishing
        run: npm install -g npm@latest

      - name: CD into nested-ci, run npm install
        run: |
          cd nested-ci
          npm install --no-audit

      - name: Set RUNNER_DEBUG env variable
        run: |
          if [[ "$RUNNER_DEBUG" == "1" ]]; then
            echo "RUNNER_DEBUG=true" >> $GITHUB_ENV
          else
            echo "RUNNER_DEBUG=false" >> $GITHUB_ENV
          fi

      - name: Printing command to run locally
        run: |
          echo 'npx ts-node src/cli.ts \
            publish-release \
            --projectName "${{ github.repository }}" \
            --ref ${{ inputs.ref }} \
            --releaseType ${{ inputs.release-type }} \
            --testRun'

      - name: Run publish
        env:
          GH_TOKEN: ${{ github.token }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
          OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
        run: |
          cd nested-ci
          npx ts-node src/cli.ts \
            publish-release \
            --projectName "${{ github.repository }}" \
            --ref ${{ inputs.ref }} \
            --releaseType ${{ inputs.release-type }}

  close-release:
    if: ${{ github.event.pull_request.merged == false && github.event.pull_request.head.repo.full_name == github.event.repository.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the rokucommunity/workflows repo
        uses: actions/checkout@master
        with:
          repository: rokucommunity/workflows
          path: nested-ci
          ref: ${{ inputs.workflows-ref }}

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '20.19.4'

      - name: CD into nested-ci, run npm install
        run: |
          cd nested-ci
          npm install --no-audit

      - name: Set RUNNER_DEBUG env variable
        run: |
          if [[ "$RUNNER_DEBUG" == "1" ]]; then
            echo "RUNNER_DEBUG=true" >> $GITHUB_ENV
          else
            echo "RUNNER_DEBUG=false" >> $GITHUB_ENV
          fi

      - name: Printing command to run locally
        run: |
          echo 'npx ts-node src/cli.ts \
            close-release \
            --projectName "${{ github.repository }}" \
            --ref ${{ github.event.pull_request.head.ref }}
            --testRun'

      - name: Run close
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd nested-ci
          npx ts-node src/cli.ts \
            close-release \
            --projectName "${{ github.repository }}" \
            --ref ${{ github.event.pull_request.head.ref }}
